# Cirrus CI configuration: #   https://cirrus-ci.com/github/libexif/libexif
# Documentation on this file: # https://cirrus-ci.org/guide/writing-tasks/
#
# SPDX-FileCopyrightText: Placed into the public domain by Dan Fandrich
# SPDX-License-Identifier: CC0-1.0

freebsd_task:
  skip: "changesIncludeOnly(
    '.appveyor.yml',
    '.github/**',
    '.reuse/*',
    'LICENSES/*'
    )"

  name: FreeBSD
  freebsd_instance:
    memory: 1400M
    matrix:
      image_family: freebsd-14-2
      image_family: freebsd-13-4

  env:
    # Set to 10 instead of 1 to avoid problems when new commits are submitted
    # during a run.
    CIRRUS_CLONE_DEPTH: 10
    CFLAGS: -Wall -Wextra -O2
    MAKEFLAGS: -j 3

  pkginstall_script:
    - pkg install -y autoconf automake libtool gettext-tools gettext-runtime
  configure_script:
    - autoreconf -sivf
    - ./configure --disable-dependency-tracking CFLAGS="$CFLAGS" || { tail -300 config.log; false; }
  compile_script:
    - make V=1
  test_script:
    - make V=1 check
  install_script:
    - make V=1 install

linux_arm_task:
  name: ARM Linux
  arm_container:
    memory: 300M
    matrix:
      image: ubuntu:22.04
      image: ubuntu:24.04

  env:
    # Set to 10 instead of 1 to avoid problems when new commits are submitted
    # during a run.
    CIRRUS_CLONE_DEPTH: 10
    CFLAGS: -Wall -Wextra -O2
    MAKE_FLAGS: -j 3

  pkginstall_script:
    - apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential autoconf automake autopoint libtool gettext
  configure_script:
    - autoreconf -sivf
    - ./configure --disable-dependency-tracking CFLAGS="$CFLAGS" || { tail -300 config.log; false; }
  compile_script:
    - make V=1
  test_script:
    - make V=1 check
  install_script:
    - make V=1 install
