#!/bin/bash

set -e

[ -z $WDY_XBUILD_ROOT ] && {
	echo "WDY_XBUILD_ROOT not set" > /dev/stderr
	exit 1
}

SRC=$(readlink -f $(dirname $0))
cd ${SRC}

autoreconf -i

TMP=$(mktemp -d)

cd ${TMP}

${WDY_XBUILD_ROOT}/bin/android-build "${SRC}" --disable-largefile --disable-nls --disable-rpath --disable-static --enable-shared

${WDY_XBUILD_ROOT}/bin/prepare_libraries.sh


